export const INIT_MAP = 'INIT_MAP';
export const FETCH_MASKDATA = 'FETCH_MASKDATA';
export const POSITIONING_PLACE = 'POSITIONING_PLACE';
export const UPDATE_AREA = 'UPDATE_AREA';
export const UPDATE_CLOSEST_STORES = 'UPDATE_CLOSEST_STORES';